server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: userTask
          uri: lb://userTask
          predicates:
            - Path=/auth/**, /users/**, /api/users/**, /

        - id: task
          uri: lb://task
          predicates:
            - Path=/api/tasks/**, /tasks/**

        - id: submissionTask
          uri: lb://submissionTask
          predicates:
            - Path=/api/submissions/**, /submissions/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
