package com.taskmanagement.userTask.config;

public class JwtConstant {
    public static final String SECRET_KEY="jnjakhfuqnruhojadajwhuqwasjvdyuqwiquwoiapinkzdvkjsbdowejgpoqfakmlkncmbcgwyfgiuwbfkjasbfmnddbfsdnbfahgfhqbwkjswehquwhdjksbduytwdeiguwkgdljsanclskncljscndquiroqiwdnasbcfjkfbaljbknjkhioqeehfipbdsksjhjagdyqisgiquaskjdbaakbahbbdqiw";
    public static final String JWT_HEADER="Authorization";
}
